[package]
name = "cjms"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"

[dependencies.uuid]
version = "1.0.0-alpha.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
]

[dev-dependencies]
actix-rt = "2"