[package]
name = "cjms"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.3"
chrono = "0.4"
config = { version = "0.12", default-features = false, features = ["yaml"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.0.0-alpha.1", features = ["v4", "fast-rng"] }

[dev-dependencies]
reqwest = "0.11.9"
serial_test = "0.6.0"
tempfile = "3.3.0"
