name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - env:
        host: "ci"
        port: "ci"
        database_url: "ci"
        environment: "ci"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cjms:$(date +%s)
